<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Bharathiraj-PC" failures="1" tests="7" name="com.zirius.qa.tests.HomePageTest" time="87.852" errors="0" timestamp="2020-08-13T01:37:08 IST" skipped="0">
  <testcase classname="com.zirius.qa.tests.HomePageTest" name="verifyAboutUsContent" time="11.830">
    <failure message="The following asserts failed:
	expected [About U] but found [About Us.]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [About U] but found [About Us.]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at com.zirius.qa.pages.HomePage.verifyAboutUsDescription(HomePage.java:173)
at com.zirius.qa.tests.HomePageTest.verifyAboutUsContent(HomePageTest.java:34)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:73)
at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)
]]>
    </failure>
  </testcase> <!-- verifyAboutUsContent -->
  <system-out/>
  <testcase classname="com.zirius.qa.tests.HomePageTest" name="verifyJobsContent" time="8.615"/>
  <system-out/>
  <testcase classname="com.zirius.qa.tests.HomePageTest" name="fillContactUsFormField" time="12.807"/>
  <system-out/>
  <testcase classname="com.zirius.qa.tests.HomePageTest" name="fillContactUsFormField" time="12.778"/>
  <system-out/>
  <testcase classname="com.zirius.qa.tests.HomePageTest" name="fillContactUsFormField" time="12.862"/>
  <system-out/>
  <testcase classname="com.zirius.qa.tests.HomePageTest" name="fillContactUsFormField" time="10.816"/>
  <system-out/>
  <testcase classname="com.zirius.qa.tests.HomePageTest" name="fillContactUsFormField" time="18.144"/>
  <system-out/>
</testsuite> <!-- com.zirius.qa.tests.HomePageTest -->
